In [3]:
## Import libraries
import yfinance as yf
import pandas as pd
import numpy as np
import time
import os
import requests

In [2]:
# CONFIG
STOCKS = ["RELIANCE.NS", "TCS.NS", "INFY.NS", "HDFCBANK.NS", "ICICIBANK.NS"]
START = "2015-01-01"
END = "2026-04-17"

os.makedirs("stock_datasets", exist_ok=True)

## Download data
for stock in STOCKS:
    print(f"\nDownloading {stock}...")

    try:
        df = yf.download(
            stock,
            start=START,
            end=END,
            progress=False,
            auto_adjust=True
        )

        if df.empty:
            print(f" No data: {stock}")
            continue

        # Fix MultiIndex
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        df = df.reset_index()
        df = df[["Date", "Open", "High", "Low", "Close", "Volume"]]

        df = df.dropna().drop_duplicates()

        file_name = f"stock_datasets/{stock.replace('.NS','')}.csv"
        df.to_csv(file_name, index=False)

        print(f" Saved {file_name} ({len(df)} rows)")

    except Exception as e:
        print(f" Error for {stock}: {e}")

    time.sleep(2)

print("\n DATA COLLECTION COMPLETE")

Downloading RELIANCE.NS...
 Saved stock_datasets/RELIANCE.csv (2786 rows)

Downloading TCS.NS...
 Saved stock_datasets/TCS.csv (2786 rows)

Downloading INFY.NS...
 Saved stock_datasets/INFY.csv (2786 rows)

Downloading HDFCBANK.NS...
 Saved stock_datasets/HDFCBANK.csv (2786 rows)

Downloading ICICIBANK.NS...
 Saved stock_datasets/ICICIBANK.csv (2786 rows)

 DATA COLLECTION COMPLETE

In [4]:
df = pd.read_csv("stock_datasets/RELIANCE.csv")

In [7]:
df.head()

         Date        Open        High         Low       Close    Volume
0  2015-01-01  189.657416  190.877140  189.090335  189.999786   2963643
1  2015-01-02  190.042601  191.743813  189.229456  189.496933   7331366
2  2015-01-05  189.379224  190.641759  187.046752  187.421234  10103941
3  2015-01-06  186.169433  186.811392  178.037884  178.915237  18627980
4  2015-01-07  179.129214  183.772746  179.107815  182.809799  20720312

In [6]:
df.tail()

            Date         Open         High          Low        Close    Volume
2781  2026-04-09  1346.000000  1350.000000  1326.300049  1330.000000  20725390
2782  2026-04-10  1337.000000  1352.300049  1331.500000  1350.199951  19364461
2783  2026-04-13  1321.199951  1327.599976  1310.000000  1315.099976  28753269
2784  2026-04-15  1337.000000  1347.000000  1334.199951  1344.099976  15313779
2785  2026-04-16  1352.000000  1353.800049  1330.000000  1343.300049  30211012