In [1]:
## Importing necessary libraries
import pandas as pd
import numpy as np

In [2]:
## Load the dataset
df = pd.read_csv("stock_datasets/RELIANCE.csv")

In [3]:
df.head()

         Date        Open        High         Low       Close    Volume
0  2015-01-01  189.657416  190.877140  189.090335  189.999786   2963643
1  2015-01-02  190.042601  191.743813  189.229456  189.496933   7331366
2  2015-01-05  189.379224  190.641759  187.046752  187.421234  10103941
3  2015-01-06  186.169433  186.811392  178.037884  178.915237  18627980
4  2015-01-07  179.129214  183.772746  179.107815  182.809799  20720312

In [4]:
df.tail()

            Date         Open         High          Low        Close    Volume
2781  2026-04-09  1346.000000  1350.000000  1326.300049  1330.000000  20725390
2782  2026-04-10  1337.000000  1352.300049  1331.500000  1350.199951  19364461
2783  2026-04-13  1321.199951  1327.599976  1310.000000  1315.099976  28753269
2784  2026-04-15  1337.000000  1347.000000  1334.199951  1344.099976  15313779
2785  2026-04-16  1352.000000  1353.800049  1330.000000  1343.300049  30211012

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.duplicated().sum()

0

In [11]:
df.dropna(inplace=True)

In [12]:
df.isnull().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [ ]:
### Data Formatting -Converted date to datetime, and sorted the data by date. 

df["Date"] = pd.to_datetime(df["Date"])
df = df.sort_values(by="Date")

In [14]:
### Column Selection- Why: Removed unnecessary columns → cleaner dataset
df = df[["Date", "Open", "High", "Low", "Close", "Volume"]]

In [ ]:
### Handling MultiIndex - Why: Yahoo data sometimes messy → needs flattening 
if isinstance(df.columns, pd.MultiIndex):
    df.columns = df.columns.get_level_values(0)

In [16]:
### Feature Engineering - Why: Added new features (e.g., daily return) → more info for models
df["Return"] = df["Close"].pct_change()
df["MA10"] = df["Close"].rolling(10).mean()

In [ ]:
# Target Variable Creation - Why: Shifted 'Close' to create target for next-day prediction
df["Target"] = df["Close"].shift(-1)

In [18]:
df.isnull().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
Return    1
MA10      9
Target    1
dtype: int64

In [19]:
df.dropna(inplace=True)

In [20]:
df.isnull().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
Return    0
MA10      0
Target    0
dtype: int64

In [21]:
### Feature Scaling - why - Needed only for deep learning models, not tree-based models. Scales features to similar range → better convergence.
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()